# Copyright FMJ Studios
# SPDX-License-Identifier: MIT

apiVersion: v2
appVersion: 2.10.1
kubeVersion: ">=1.26"
name: paperless-ngx
version: 0.2.1
dependencies:
  - name: postgresql
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.enabled
    version: ~15.5
  - name: redis
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: redis.enabled
    version: ~19.5
  - name: tika
    repository: https://apache.jfrog.io/artifactory/tika
    condition: tika.enabled
    version: ~2.9
  - name: gotenberg
    repository: oci://ghcr.io/fmjstudios/helm
    condition: gotenberg.enabled
    version: ~0.0.1
description: Paperless-NGX is a community-supported supercharged version of paperless - scan, index and archive all your physical documents
home: https://github.com/paperless-ngx/paperless-ngx
icon: https://raw.githubusercontent.com/fmjstudios/artwork/76af35c64fd93c12e851925b0d3801e89978f05a/projects/paperless-ngx/icon/color/paperless-ngx-icon-color.png
keywords:
  - documents
  - archival
  - ocr
  - conversion
  - paper
  - paperless
sources:
  - "https://github.com/fmjstudios/helm"
maintainers:
  - name: FMJ Studios Helm Authors
    email: info@fmj.studio
  - name: FMJdev
    email: info@fmj.dev
annotations:
  artifacthub.io/category: storage
  artifacthub.io/license: MIT
  artifacthub.io/signKey: |
    fingerprint: 654213659810F05D16A7EDECB6C4D653E669D643
    url: https://keys.openpgp.org/vks/v1/by-fingerprint/654213659810F05D16A7EDECB6C4D653E669D643
  artifacthub.io/prerelease: "false"
  artifacthub.io/images: |
    - name: paperless-ngx
      image: ghcr.io/paperless-ngx/paperless-ngx:2.4.0
  artifacthub.io/links: |
    - name: Source
      url: https://github.com/fmjstudios/helm
    - name: Support
      url: https://github.com/fmjstudios/helm/issues
    - name: Paperless-NGX GitHub Repository
      url: https://github.com/paperless-ngx/paperless-ngx
    - name: Paperless-NGX Documentation
      url: https://docs.paperless-ngx.com/
  org.opencontainers.image.vendor: "FMJ Studios"
  org.opencontainers.image.licenses: "MIT"
  # ref: https://artifacthub.io/docs/topics/annotations/helm/
  artifacthub.io/changes: |
    - kind: fixed
      description: add missing namespace references
    - kind: added
      description: volumes and volumeMounts configuration within values.yaml
    - kind: changed
      description: updated values.schema.json